<a name="JCAxf"></a>
## 18.1 JavaScript的错误类型
在最初第二章：《2.1 语法错误和通用错误》曾经简单的提到，本章会做一个完全的补充。
<a name="mqOEE"></a>
### 18.1.1 SyntaxError：语法错误
```javascript
// (1)非法变量名；变量名不可以数字开头
var 1 = 1; // Uncaught SyntaxError:Unexpected number 意外的数字
var 1ab = 1; // Uncaught SyntaxError:Invalid or unexpected token 意外的标记

// (2)关键字不能赋值操作
new = 5; // Uncaught SyntaxError:Unexpected token '=' 意外的等号标识
function = 5; // Uncaught SynataxError:Unexpected token '=' 

// (3)基本的语法错误
var a = 5: // Uncaught SynataxError:Unexpected token ':'
function 1test(){} // Uncaught SyntaxError:Invalid or unexpected token 意外的标记
```
<a name="aQIDA"></a>
### 18.1.2 ReferenceError：引用错误
```javascript
// 变量或者函数未被声明

// (1)给无法被赋值的对象赋值的时候
var a = 1 = 2; // Uncaught ReferenceError:Invalid left-hand side in assignment 赋值中的左侧无效

console.log(a) = 1; // Uncaught ReferenceError:a is not defined a没有被定义
```
<a name="VA680"></a>
### 18.1.3 RangeError：范围错误
```javascript
// 数组长度为负数的时候
// 对象方法参数超出可行范围

var arr = [1, 2, 3];
arr.length = -1;
console.log(arr); // Uncaught RangeError: Invalid array length

var num = new Number(66.66);
console.log(num.toFixed(-1)); 
// Uncaught RangeError:toFixed() digits arguments must be between 0 and 100 
// => toFixed参数错误,参数的范围在0 - 100之间
```
<a name="qmacv"></a>
### 18.1.4 TypeError：类型错误
```javascript
// (1)调用不存在的方法
test(); // Uncaught ReferenceError:test is not denfined
123(); // Uncaught TypeError: 123 is not a function
/**
* 为什么上述一个是ReferenceError而另一个是TypeError？ 答案在于JS引擎解析时,test是一个变量,而123则是个表达式；
* 全局中没有定义过名为test的变量,所以报的是引用类型错误；而123本身就不是函数,所以报的是类型错误。
*/

var obj = {};
obj.say; // 引擎认为say是属性,不会报错
obj.say(); // 引擎认为say是属性,但是say不是函数,所以属性执行报类型错误, Uncaugth TypeError:obj.say is not a function

// (2)实例化原始值
var a = new 'string'; // Uncaugth TypeError:'string' is not a constructor
var a = new 123; // Uncaught TypeError:'123' is not a constructor
```
<a name="jSRXc"></a>
### 18.1.5 URIError：URI错误
```javascript
// URL：UNIFORM RESOURCE LOCATOR 统一资源定位符
// URN：UNIFORM RESOURCE NAME 统一资源名称
// URI：UNIFORM RESOURCE IDENTIFER 统一资源标识符

// URL：http://www.baidu.com/new#today
//		  ftp://www.baidu.com/ftp#developer
// URN: //www.baidu.com/ftp#developer

// => URL和URN是URI的子集。[会在网络部分的章节中补充]

var myurl = 'http://www.baidu.cin?name=林俊杰';
// 把中文字转为中文编码字符
var newUrl = encodeURI(myurl); 
console.log(newUrl); // http://www.baidu.cin?name=%E7%88%B1%E7%AC%91%E4%B9%9F
// 把中文编码字符转为中文
var newNewUrl = decodeURI(newUrl);
console.log(newNewUrl); // 'http://www.baidu.cin?name=林俊杰'

// 自定义字符编码导致报错
var str = decodeURI('%fdasd'); 
// Uncaught URIError: URL malformed at decodeURI decodeURI处的URL格式不正确
```
<a name="NS0HN"></a>
### 18.1.6 EvalError：eval函数执行错误
```javascript
// eval('字符串脚本引擎')函数:JS程序写成字符串,然后放入eval方法中即可执行。
eval('var a = 1; console.log(a)'); // 1

// eval()方法最大的用处,将JSON字符串转为JS对象,但是现在用JSON.parse方法代替
var jsonData = '['+
    '{' +
				'"name":"abc"'+
    '},'+
    '{' +
    		'"name":"bcd"'+
    '},'+
    '{' +
    		'"name":"efg"'+
    '},'+
    ']';
var data = eval('('+ jsonData +')');
console.log(data); // JS对象形式, 因为eval函数现在不容易出错,所以不验证了。
// 需要注意的是，一般生产情况下最好不要使用eval，和input标签一样很容易收到外部攻击
```
<a name="XEDby"></a>
## 18.2 系统自动抛出错误 || 人为抛出错误
<a name="Or16t"></a>
### 18.2.1 自定义错误类型
```javascript
// 人为抛出错误,通过各类错误的构造函数进行构造错误的实例化对象。
var error = new Error('代码错误');
var error = new TypeError('类型错误');
var error = new ReferenceError('引用错误');

// 系统自动抛出错误,没有任何方式处理系统抛出的错误
console.log('执行1'); // 执行1
console.log(a); // Uncaugth ReferenceError: a is not defined 
console.log('执行2') // 因为上面一行报错了,后面的代码将全部阻塞
```
<a name="vp5SB"></a>
### 18.2.2 手动抛出错误的方式
```javascript
// try  catch
// try_catch语句处理手动抛出错误的问题。
// try catch finally throw

try {
	console.log('执行1'); // 执行1
  console.log(a); // Uncaught ReferenceError: a is not defined
  console.log('执行2'); // 不执行
} catch(e) {
	console.log(e.name + ':' + e.message);
} finally {
	console.log('执行3'); // 执行3
}
console.log('执行4'); // 执行4

/** 总结：
*   catch语句能够捕获到try语句中的错误,并且打印出来。e.name:错误类型 e.message:错误信息；
*   try里面的错误不影响外部代码执行,也不影响finally(一定会执行)里的代码程序。
*/

// 实例: 因为网络影响,可能后端传递的JsonStr未获取到
var jsonStr = '';
try	{
	if(jsonStr === '') {
  	throw 'JSON字符串为空'; // throw自定义抛出错误信息。
    throw new Error(); // 手动抛出错误。
  }
  console.log('执行1');
  var json = JSON.parse(jsonStr); // JSON数据转为JS对象,如果参数为''字符串报错																							 SyntaxError: Unexpected end of JSON input
  console.log(json);
} catch(e) {
  // 捕获throw抛出的错误
  console.log(e); // JSON字符串为空
  // 错误的结果集合;这里一般根据后端返回的来
  var errorTip = {
  	name:'数据传输失败',
    errorCode:'10010'
  }
  console.log(errorTip);
}
```
<a name="O5qCg"></a>
## 18.3 严格模式基础
<a name="aE1TD"></a>
### 18.3.1 ECMAScript历程
```javascript
ECMAScript DOM BOM

1997 ---> 发布 1.0
1998 ---> 2.0
1999 ---> 3.0 JS通行的标准
2007 ---> 4.0 草案 mozilla公司支持(Branden Eich),其他浏览器厂商不支持
2008 ---> 4.0 由于比较激进终止  容易改善的部分定为3.1  激进的部分定为Harmony
					结合容易改善的3.1发布ECMAScript 5
2009 ---> 发布ECMAScript 5.0, 定义Harmony ---> 1/2 JS.NEXT  1/2 JS.NEXT.NEXT
2011 ---> 5.1 ISO国际标准
2013 ---> ES6 不再增添任何东西 == JS.NEXT   ES7就是 ---> 1/2 JS.NEXT.NEXT
		 ---> ES6 草案发布
2015 ---> ES6正式发布,ECMAScript2015
```
<a name="NpLE8"></a>
### 18.3.2 开启严格模式
```javascript
// ES5：正常模式 || 严格模式
// IE9以及以下IE不支持严格模式
// 严格模式作用:按照ES5的语法规范执行代码

// 声明方式:全局环境第一行或者函数内部第一行'use strict' ------> 为什么是字符串的形式呢?
'use strict'是表达式,如果其他浏览器版本不支持的话,表达式是不会报错的。
```
<a name="lTA67"></a>
### 18.3.3 with() 
```javascript
var a = 1;
var obj = {
	a: 2
}
function test() {
	var a = 3;
	var b = 4;
	with(obj) {
		console.log(a); // 2
		console.log(b); // 4
	}
}
test();



// 严格模式下报错:Uncaught SyntaxError: Strict mode code may not include a with statement
var a = 1;
var obj = {
	a: 2
}
function test() {
	var a = 3;
	var b = 4;
	with(obj) {
		console.log(a); // 2
		console.log(b); // 4
	}
}
test();

```
```javascript
// 命名冲突
var a = 1;
var a = 2;
console.log(a);
function test() {
	console.log(1);
}
function test() {
	console.log(2);
}
test();

// with()解决:
var namespace = {
	header: {
  	Jenny:{
    	a:1,
      b:2
    },
    Ben:{
    	a:1,
      b:2
    }
  }
}

// 正常调用
console.log(namespace.header.Ben.a);
// with
with(namespace.header.Ben) {
	console.log(a);
}

// 现在一般通过利用模块化开发方法或webpack[webpack专题会补充]
var initProgarmmer = (function(){})();
```
<a name="UCz8U"></a>
## 18.4 严格模式&&非严格模式的场景
```javascript
// 非严格模式下:
function test() {
	console.log(this); // window
}
test.call(1); 
// Number { 1 } test.call()：改变this指向,this指向的是对象,所以1被包装类隐式的转换成数字对象的形式。

function test(a, a) {
	console.log(a); // 2
}
test(1, 2);

eval('var a = 1; console.log(a)'); // 1

/** ECMAScript严格模式下需要注意什么呢？
* 1. with(){}语句不可用,因为改变作用域。
* 2. callee,caller不可用,但是arguments可以使用。
* 3. a = 1; 变量必须声明,不然报错 ReferenceError; => var a; a = 1;
* 4. var a = b = 1; 变量必须声明
* 5. window环境下,this指向undefined,所以函数默认this也是指向undefined。
* 6. 函数的参数不能重复声明
* 7. eval()函数有自己的作用域,外界此时访问不到内部。
*/

// 但有一点很特殊 => 无论严格模式还是非严格模式,对象属性重复声明都不会报错。这里可能会有对应的面试题
var obj = {
	a: 1,
	a: 2
}
console.log(obj.a); // 2


```
<a name="cIkZJ"></a>
## 18.5 补充一下对象的[]语法
```javascript
var name = 'abc'
Object.prototype.name = 'ObjectName'
var obj = {
	a: 1,
  name: 'obj',
  ObjectName: 'objectName'
}

obj[a]; // Uncaught ReferenceError: a is not defined
obj[name]; // undefined; 
// obj[name] ---> name是外界的一个变量。r如果外界存在var name = 'abc' => 则变成了obj['abc']。
obj['name']; // obj
obj.name; // obj； JS引擎会做一次隐式转换 => obj['name']

// 根据上面的结论,现在obj[name]是undefined,而为什么不报错呢?
// 在JavaScript引擎执行时,obj[name] ---> 是外界的一个变量,所以会寻找name存储的值,
// 此时和obj的prototype并没有关系,并不会去prototype上寻找。
// name只会在作用域中寻找属于自己的值,顺着作用域链寻找,在window对象GO环境中挂载着name属性,并且属性值是""空字符串,
// 所以obj[name]---> obj[window.name] --> obj[''] ---> undefined。


// 关于name:
// name具有特殊之处，它不是javascript的关键字字(保留字在某种意思上是为将来的关键字而保留的留字也不能被用作变量名或函数名) 
// 页面在IE浏常,但是Safari , chrome , Firefox和Opera这函数定义了一个非标准的name属性:"",是window的保留字所以在全局声明name变量名会出现访问异常问题
```
